### PR TITLE
Hours 18

### PR DESCRIPTION
**Pull request by barmintor**
locations can be assigned a primary location by administrators on create and update
primary locations are linked from location calendar
open_now filters by primary location closure

### CODE REVIEW

**Review by JackBlackLight — COMMENTED** [review]
Ben - is open_at in the timetable model being called anywhere? Or was it made obsolete by your revision to open_now in location_controller?

**Comment by barmintor** [comment]
@JackBlackLight that's a good question- I think it might be obsolete now.

**Comment by JackBlackLight** [comment]
Other than that, everything looks great.

**Review by cgalarza — APPROVED** [review]
This looks great. 👍

**Pull request merged**
