### PR TITLE
fold open_now display into home page

### PR DESCRIPTION
**Pull request by barmintor**
This is kind of slow, so we definitely want to cache this (or just use SQL over ActiveRecord), but it displays the open status on the homepage.

### CODE REVIEW

**Comment by barmintor** [comment]
(it's deployed to dev)

**Comment by er-k** [comment]
i think it looks great and will make folks happy. 

would be good if we could add a class to differentiate shade/color between open and closed. on the parent span tag or if that's a pain then by wrapping the "closed" message in a span tag with a class of "is-closed" would be great.

**Comment by barmintor** [comment]
I'll add a class="is-closed" to the parent LI if you have a presentation in mind, sure.

**Comment by er-k** [comment]
would you be able to add "is-closed" to the parent SPAN (in addition to it's class of closes-at)?

**Comment by barmintor** [comment]
sure

**Review by er-k — APPROVED** [review]

**Pull request merged**
